-- =============================================
-- 1. subscription_plan
-- =============================================
CREATE TABLE IF NOT EXISTS subscription_plan (
    plan_id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plan_code     VARCHAR(50),
    plan_name     VARCHAR(100) NOT NULL,
    price         INTEGER NOT NULL DEFAULT 0 CHECK (price >= 0),
    duration_day  INTEGER NOT NULL CHECK (duration_day > 0),
    description   VARCHAR(200)
);

-- =============================================
-- 2. users
-- =============================================
CREATE TABLE IF NOT EXISTS users (
    user_id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_code         VARCHAR(50) NOT NULL UNIQUE,
    username          VARCHAR(40) NOT NULL UNIQUE,
    gender           VARCHAR(20),
    country           VARCHAR(100) NOT NULL,
    email             VARCHAR(100) UNIQUE NOT NULL,
    password_hash     TEXT NOT NULL,
    display_name      VARCHAR(40) NOT NULL,
    profile_image_url VARCHAR(255),
    role              VARCHAR(40) NOT NULL CHECK (role IN ('user','admin','super_admin')),
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- =============================================
-- 3. transactions
-- =============================================
CREATE TABLE IF NOT EXISTS transactions (
    transaction_id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id          INTEGER NOT NULL,
    transactions_code VARCHAR(50),     
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status           VARCHAR(10) DEFAULT 'completed',
    currency         VARCHAR(5) DEFAULT 'THB',
    payment_method   VARCHAR(20),
    CONSTRAINT fk_user_transaction FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- =============================================
-- 4. transaction_detail
-- =============================================
CREATE TABLE IF NOT EXISTS transaction_detail (
    transaction_id INTEGER NOT NULL,
    detail_id      INTEGER NOT NULL,
    plan_id        INTEGER NOT NULL,
    unit_price     INTEGER NOT NULL CHECK (unit_price >= 0),
    quantity       INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    period_covered DATE,

    PRIMARY KEY (transaction_id, detail_id),
    CONSTRAINT fk_transaction FOREIGN KEY (transaction_id) REFERENCES transactions(transaction_id),
    CONSTRAINT fk_plan_detail FOREIGN KEY (plan_id) REFERENCES subscription_plan(plan_id)
);

-- =============================================
-- 5. user_subscription
-- =============================================
CREATE TABLE IF NOT EXISTS user_subscription (
    user_id         INTEGER NOT NULL,
    subscription_id INTEGER NOT NULL,
    plan_id         INTEGER NOT NULL,
    transaction_id  INTEGER,
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL CHECK (end_date >= start_date),
    status          VARCHAR(10) NOT NULL DEFAULT 'active',
    PRIMARY KEY (user_id, subscription_id),
    CONSTRAINT fk_user_sub FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_plan_sub FOREIGN KEY (plan_id) REFERENCES subscription_plan(plan_id),
    CONSTRAINT fk_transaction_sub FOREIGN KEY (transaction_id) REFERENCES transactions(transaction_id)
);

-- =============================================
-- 6. artist
-- =============================================
CREATE TABLE IF NOT EXISTS artist (
    artist_id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    artist_code       VARCHAR(50) NOT NULL UNIQUE,
    artist_name       VARCHAR(255) NOT NULL,
    gender            VARCHAR(30) CHECK (gender IN ('Male','Female','Other')),
    type              VARCHAR(30) NOT NULL,
    bio               VARCHAR(255),
    debut_year        VARCHAR(4) CHECK (debut_year ~ '^[0-9]{4}$'),
    profile_image_url VARCHAR(255),
    verified_status   BOOLEAN DEFAULT FALSE
);

-- =============================================
-- 7. album
-- =============================================
CREATE TABLE IF NOT EXISTS album (
    album_id        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    artist_id       INTEGER NOT NULL,
    album_code      VARCHAR(50) NOT NULL CHECK (char_length(album_code) >= 3),
    album_name      VARCHAR(100) NOT NULL,
    album_type      VARCHAR(100) NOT NULL CHECK (album_type IN ('single','ep','album')),
    release_date    DATE NOT NULL,
    cover_image_url VARCHAR(255),
    CONSTRAINT fk_artist_album FOREIGN KEY (artist_id) REFERENCES artist(artist_id)
);

-- =============================================
-- 8. genre
-- =============================================
CREATE TABLE IF NOT EXISTS genre (
    genre_id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    genre_name  VARCHAR(255)  NOT NULL,
    description VARCHAR(255)
);

-- =============================================
-- 9. music
-- =============================================
CREATE TABLE IF NOT EXISTS music (
    music_id     INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    album_id     INTEGER NOT NULL,
    music_code   VARCHAR(50) NOT NULL UNIQUE,
    title        VARCHAR(255) NOT NULL,
    release_date DATE NOT NULL,
    duration     INTEGER NOT NULL CHECK (duration > 0),
    track_number INTEGER CHECK (track_number > 0),
    file_url     VARCHAR(255) NOT NULL,
    play_count   BIGINT NOT NULL DEFAULT 0,
    is_explicit  BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_album_music FOREIGN KEY (album_id) REFERENCES album(album_id)
);

-- =============================================
-- 10. music_artist
-- =============================================
CREATE TABLE IF NOT EXISTS music_artist (
    music_id  INTEGER NOT NULL,
    artist_id INTEGER NOT NULL,
    role      VARCHAR(255) DEFAULT 'Main Artist',
    PRIMARY KEY (music_id, artist_id),
    CONSTRAINT fk_music_ma FOREIGN KEY (music_id) REFERENCES music(music_id),
    CONSTRAINT fk_artist_ma FOREIGN KEY (artist_id) REFERENCES artist(artist_id)
);

-- =============================================
-- 11. music_genre
-- =============================================
CREATE TABLE IF NOT EXISTS music_genre (
    music_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    PRIMARY KEY (music_id, genre_id),
    CONSTRAINT fk_music_mg FOREIGN KEY (music_id) REFERENCES music(music_id),
    CONSTRAINT fk_genre_mg FOREIGN KEY (genre_id) REFERENCES genre(genre_id)
);

-- =============================================
-- 12. playlist
-- =============================================
CREATE TABLE IF NOT EXISTS playlist (
    playlist_id     INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id         INTEGER NOT NULL,
    playlist_code   VARCHAR(50) NOT NULL UNIQUE,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(100),
    is_public       BOOLEAN NOT NULL DEFAULT TRUE,
    date            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cover_image_url VARCHAR(255),
    CONSTRAINT fk_user_playlist FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- =============================================
-- 13. playlist_items
-- =============================================
CREATE TABLE IF NOT EXISTS playlist_items (
    playlist_id INTEGER NOT NULL,
    sequence_no INTEGER NOT NULL CHECK (sequence_no > 0),
    music_id    INTEGER NOT NULL,
    added_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (playlist_id, sequence_no),
    CONSTRAINT fk_playlist_items FOREIGN KEY (playlist_id) REFERENCES playlist(playlist_id),
    CONSTRAINT fk_music_items FOREIGN KEY (music_id) REFERENCES music(music_id)
);

-- =============================================
-- 14. librarys
-- =============================================
CREATE TABLE IF NOT EXISTS librarys (
    user_id         INTEGER PRIMARY KEY,
    total_albums    INTEGER DEFAULT 0,
    total_artists   INTEGER DEFAULT 0,
    total_playlists INTEGER DEFAULT 0,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_library FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- =============================================
-- 15. library_albums
-- =============================================
CREATE TABLE IF NOT EXISTS library_albums (
    lib_album_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    album_id     INTEGER NOT NULL,
    user_id      INTEGER NOT NULL,
    added_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_album_lib FOREIGN KEY (album_id) REFERENCES album(album_id),
    CONSTRAINT fk_user_lib_album FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- =============================================
-- 16. library_artist
-- =============================================
CREATE TABLE IF NOT EXISTS library_artist (
    lib_artist_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    artist_id     INTEGER NOT NULL,
    user_id       INTEGER NOT NULL,
    followed_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_artist_lib FOREIGN KEY (artist_id) REFERENCES artist(artist_id),
    CONSTRAINT fk_user_lib_artist FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- =============================================
-- 17. library_playlist
-- =============================================
CREATE TABLE IF NOT EXISTS library_playlist (
    lib_playlist_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    playlist_id     INTEGER NOT NULL,
    user_id         INTEGER NOT NULL,
    saved_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_owner        BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_playlist_lib FOREIGN KEY (playlist_id) REFERENCES playlist(playlist_id),
    CONSTRAINT fk_user_lib_playlist FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- =============================================
-- 18. listen_history
-- =============================================
CREATE TABLE IF NOT EXISTS listen_history (
    history_id      INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id         INTEGER NOT NULL,
    music_id        INTEGER NOT NULL,
    played_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration_played INTEGER NOT NULL CHECK (duration_played >= 0),
    CONSTRAINT fk_user_history FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_music_history FOREIGN KEY (music_id) REFERENCES music(music_id)
);

-- =============================================
-- 19. user_activity_log
-- =============================================
CREATE TABLE IF NOT EXISTS user_activity_log (
    activity_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id     INTEGER NOT NULL,
    music_id    INTEGER,
    action_type VARCHAR(50) NOT NULL CHECK (action_type IN ('play','stop','search','like','skip')),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_log FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- =============================================
-- 20. recommend
-- =============================================
CREATE TABLE IF NOT EXISTS recommend (
    user_id     INTEGER NOT NULL,
    music_id    INTEGER NOT NULL,
    score       DECIMAL(2,1) CHECK (score >= 0.0 AND score <= 5.0),
    reason      VARCHAR(255),
    generate_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, music_id),
    CONSTRAINT fk_user_rec FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_music_rec FOREIGN KEY (music_id) REFERENCES music(music_id)
);

-- =============================================
-- 21. reviews
-- =============================================
CREATE TABLE IF NOT EXISTS reviews (
    review_id  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    INTEGER NOT NULL,
    music_id   INTEGER NOT NULL,
    rating     INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment    VARCHAR(100),
    create_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_review FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_music_review FOREIGN KEY (music_id) REFERENCES music(music_id)
);

-- =============================================
-- 22. chart
-- =============================================
CREATE TABLE IF NOT EXISTS chart (
    chart_id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chart_code  VARCHAR(100) UNIQUE ,
    chart_name  VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    chart_date  DATE DEFAULT CURRENT_DATE
);

-- =============================================
-- 23. music_chart
-- =============================================
CREATE TABLE IF NOT EXISTS music_chart (
    chart_id  INTEGER NOT NULL,
    music_id  INTEGER NOT NULL,
    entry_date DATE,
    last_rank INTEGER CHECK (last_rank > 0),
    peak_rank INTEGER CHECK (peak_rank > 0 AND peak_rank <= last_rank),
    PRIMARY KEY (chart_id, music_id),
    CONSTRAINT fk_chart_mc FOREIGN KEY (chart_id) REFERENCES chart(chart_id),
    CONSTRAINT fk_music_mc FOREIGN KEY (music_id) REFERENCES music(music_id)
);